name: Deploy website

on:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Deploy to surgh.sh
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: Setup environment
      run: npm install
    - name: Install surge.sh
      run: npm install -g surge      
    - name: Deploy to surge.sh
      run: surge ./src ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN}}
